name: sealed_generator
description: A new Flutter package.
version: 0.0.1
homepage: https://github.com/xsahil03x/sealed_ugh

authors:
  - Sahil Kumar <xdsahil@gmail.com>
  - Jai Sachdeva <sachdeva.jai@outlook.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sealed:
    path: ../sealed/
  source_gen: ^0.9.4+6

dev_dependencies:
  build_runner: ^1.7.1
  source_gen_test: ^0.1.0+6
  test: ^1.3.3