name: sealed_generator
description: A new Flutter package.
version: 0.0.1
homepage: https://github.com/xsahil03x/sealed_ugh

authors:
  - Sahil Kumar <xdsahil@gmail.com>
  - Jai Sachdeva <sachdeva.jai@outlook.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^0.9.4+6
  sealed:
    path: ../sealed/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1

flutter:
