name: sealed
description: A new Flutter package.
version: 0.0.1
homepage: https://github.com/xsahil03x/sealed_ugh

authors:
  - Sahil Kumar <xdsahil@gmail.com>
  - Jai Sachdeva <sachdeva.jai@outlook.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.7
