name: sealed
description: Create super-powered enums similar to sealed classes in Kotlin.
version: 0.0.1
homepage: https://github.com/xsahil03x/sealed.dart

authors:
  - Sahil Kumar <xdsahil@gmail.com>
  - Jai Sachdeva <sachdeva.jai@outlook.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
