name: super_enum_generator
description: Dev-dependency to generate sealed classes and when statements together with the super_enum.dart package.
version: 0.7.0
homepage: https://github.com/xsahil03x/super_enum

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  # Specify a specific version or a version constraint
  # for "super_enum" before publishing the package.
  super_enum:
    path: ../super_enum
  source_gen: ^1.2.2
  analyzer: ^4.1.0
  build: ^2.3.0
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.21.1
  build_runner: ^2.1.11
  source_gen_test: ^1.0.3
