targets:
  $default:
    builders:
      sealed_ugh_generator|sealed_ugh:
        enabled: true

builders:
  sealed_ugh_generator:
    target: ":sealed_ugh_generator"
    import: "package:sealed_ugh_generator/sealed_ugh_generator.dart"
    builder_factories: ["sealedUghGeneratorFactory"]
    build_extensions: {".dart": [".sealed_ugh.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]